In [1]:
import pandas as pd
import numpy as np
import requests
import json

api = "87594855563381b8f9fa3b3224c9f19f"
idURL = "https://api.themoviedb.org/3/search/movie?query="
idURL1 = "&api_key="
detailURL = "https://api.themoviedb.org/3/movie/"
detailURL1 = "?api_key="

In [2]:
csvPath = 'opening_weekend.csv'
opening = pd.read_csv(csvPath)
print(len(opening))
opening.head()

175

,Title,Studio,Weekend Gross,% Change,Theater Count / Change,Unnamed: 5,Average,Total Gross,Budget*,Week #
0,Star Wars: The Last Jedi,BV,220009584,-,4232,-,51987,220009584,-,1
1,Thor: Ragnarok,BV,122744989,-,4080,-,30085,122744989,180,1
2,Justice League,WB,93842239,-,4051,-,23165,93842239,-,1
3,Black Panther,BV,202003951,-,4020,-,50250,202003951,-,1
4,Coco,BV,50802605,-,3987,-,12742,72908930,-,1

In [3]:
# movies = opening['Title']
# print (movies)

idList = []
movieNames = []
movieList = []
grossList = []
openingMovies = []

for index, row in opening.iterrows():
    movie = row['Title']
#     finalMovie = movie.replace(":","")
#     finalMovie = movie.replace(" ","%20")
    gross = row['Weekend Gross']
    finalURL = idURL + movie + idURL1 + api
#     print (finalURL)
    json_file = requests.get(finalURL).json()
    moviesJSON = json_file['results']
#     print (moviesJSON)
#     print (len(json_file['results']))
    
    try:
        dates = []
        for n in np.arange(len(moviesJSON)):
#             print (n)
            date = moviesJSON[n]['release_date']
            date = int(date.replace("-",""))
#             print (date)
            dates.append(date)   
#         print (dates)      
#         print (recent)
    except:
        pass        
 
    try:
#         print(f'{dates}')
        new = max(dates)
        newestMovie = dates.index(new)
        recentMovie = moviesJSON[newestMovie]
        idNumber = recentMovie['id']
    #         movie = recentMovie['original_title']
        grossList.append(gross)
        movieNames.append(movie)
        idList.append(idNumber)
    except ValueError:
        pass
    
#     print(f'{movie} / {max(dates)} / {newestMovie} / {idNumber} / {gross}')
#     print('--------------------------------------------------------------------------------')
    
openingMoviesDF = pd.DataFrame({"movies":movieNames, "gross":grossList, "id_number":idList})
print (len(openingMoviesDF))
openingMoviesDF.head(50)

175

        gross  id_number                                      movies
0   220009584     181808                    Star Wars: The Last Jedi
1   122744989     284053                              Thor: Ragnarok
2    93842239     417602                              Justice League
3   202003951     284054                               Black Panther
4    50802605     354912                                        Coco
5    24167011     336843                 Maze Runner: The Death Cure
6    38560195     337167                          Fifty Shades Freed
7    36169328     353486              Jumanji: Welcome to the Jungle
8    25010928     381719                                Peter Rabbit
9    11001961     346648                                Paddington 2
10   13401586     364689                                   Ferdinand
11   16759161     431530                        A Bad Moms Christmas
12   29651193     419680                              Daddy's Home 2
13   17005332     505058                                  Game Night
14   19928525     353616                             Pitch Perfect 3
15   29581355     406563                     Insidious: The Last Key
16   27547866     464052                                      Wonder
17   16853422     401981                                 Red Sparrow
18   12554286     453201                          The 15:17 to Paris
19    8805843     316029                        The Greatest Showman
20   15815025     429351                                   12 Strong
21   16640452     298250                                      Jigsaw
22    3287451     354861                              Father Figures
23   13701452     399035                                The Commuter
24    9812674     181808                                    The Star
25    4954287     301337                                  Downsizing
26    3190525     387592                                   Early Man
27    9307626     416234                                  Winchester
28   15206108     449443                              Den of Thieves
29    3201459     398177                        Just Getting Started
30    9959053     442064                                  Proud Mary
31    5584684     446791                  All the Money in the World
32    2840246     395458                                  Suburbicon
33   11071584     300668                                Annihilation
34    1942569     474392                                      Samson
35    4245630     417261                             Forever My Girl
36    1110565     353575                                         LBJ
37    1357129     450322              The Man Who Invented Christmas
38     156288     502774  Little Shop of Horrors: The Director's Cut
39    1729535     480881                          Let there be Light
40    1147073     498919                        La Boda de Valentina
41    4493384     432527                                   Padmaavat
42     309951     332718                  Bilal: A New Breed of Hero
43    1787108     441909                             Tiger Zinda Hai
44     144076     345923                            All I See is You
45    2349967     396371                                Molly's Game
46      99541     481367                    But Deliver Us from Evil
47     348475     430447                 Mary and the Witch's Flower
48     248456     450314                      Condorito: La Pelicula
49     740313     447856                                     Pad Man

In [4]:
for index, movie in openingMoviesDF.iterrows():
    detailsURL = detailURL + str(movie['id_number']) + detailURL1 + api
#     print (detailsURL)
    details = requests.get(detailsURL).json()
#     print(details)
    title = details['original_title']
#         print (title)
    budget = details['budget']
    rating = details['vote_average']
    release = details['release_date']
    weekendGross = movie['gross']
    try:
        genre = details['genres'][0]['name']
    except:
        genre = "N/A"
#     print (genre)
    movieDict = {"name": title, "gross":weekendGross, "rating": rating, "budget": budget, "release date": release, "genre":genre}
    movieList.append(movieDict)
    
moviesDF = pd.DataFrame(movieList)

In [5]:
moviesDF = moviesDF.sort_values('budget', ascending = False)
print (len(moviesDF))
moviesDF.head(50)

175

,budget,genre,gross,name,rating,release date
9,204581644,Adventure,11001961,Paddington 2,7.8,2017-11-09
0,200000000,Action,220009584,Star Wars: The Last Jedi,7.2,2017-12-13
3,200000000,Action,202003951,Black Panther,7.4,2018-02-13
24,200000000,Action,9812674,Star Wars: The Last Jedi,7.2,2017-12-13
1,180000000,Science Fiction,122744989,Thor: Ragnarok,7.4,2017-10-25
4,175000000,Adventure,50802605,Coco,7.8,2017-10-27
10,111000000,Animation,13401586,Ferdinand,6.8,2017-12-09
7,90000000,Action,36169328,Jumanji: Welcome to the Jungle,6.5,2017-12-09
19,84000000,Drama,8805843,The Greatest Showman,8.1,2017-12-20
58,73000000,Action,95577,西游记·女儿国,0.0,2018-05-18
17,69000000,Mystery,16853422,Red Sparrow,6.4,2018-03-01
12,69000000,Comedy,29651193,Daddy's Home 2,5.8,2017-11-09
25,68000000,Comedy,4954287,Downsizing,5.2,2017-12-22
5,62000000,Action,24167011,Maze Runner: The Death Cure,7.3,2018-01-17
106,55000000,Adventure,22849,Hostiles,5.4,2017-12-22
6,55000000,Drama,38560195,Fifty Shades Freed,6.2,2018-02-07
33,55000000,Mystery,11071584,Annihilation,5.7,2018-02-22
8,50000000,Animation,25010928,Peter Rabbit,5.4,2018-02-07
31,50000000,Crime,5584684,All the Money in the World,6.3,2017-12-21
26,50000000,Family,3190525,Early Man,5.6,2018-01-26
14,45000000,Comedy,19928525,Pitch Perfect 3,6.5,2017-12-21
88,35000000,Drama,216495,Phantom Thread,7.3,2017-12-25
45,30000000,Crime,2349967,Molly's Game,6.9,2017-12-21
93,30000000,Drama,175006,Darkest Hour,7.2,2017-11-22
42,30000000,Action,309951,Bilal: A New Breed of Hero,7.2,2015-12-09
28,30000000,Action,15206108,Den of Thieves,5.9,2018-01-18
23,30000000,Action,13701452,The Commuter,5.7,2018-01-11
18,30000000,Drama,12554286,The 15:17 to Paris,5.1,2018-02-02
11,28000000,Comedy,16759161,A Bad Moms Christmas,6.1,2017-11-01
22,25000000,Comedy,3287451,Father Figures,4.9,2017-12-21
29,22000000,Action,3201459,Just Getting Started,5.5,2017-12-01
96,22000000,Crime,61999,"Roman J. Israel, Esq.",5.8,2017-11-10
116,19500000,Drama,166564,The Shape of Water,7.4,2017-12-01
43,15000000,Action,1787108,टाइगर ज़िंदा है,6.5,2017-12-18
91,15000000,Crime,322168,"Three Billboards Outside Ebbing, Missouri",8.2,2017-11-10
30,14000000,Thriller,9959053,Proud Mary,5.2,2018-01-12
105,13600000,Drama,23091,Happy End,6.6,2017-10-04
74,13000000,Action,3061,Kickboxer: Retaliation,5.3,2018-01-26
92,11000000,Drama,264155,"I, Tonya",7.5,2017-12-08
51,10778400,Animation,4028,Tadeo Jones 2: El secreto del rey Midas,6.2,2017-08-25
15,10000000,Mystery,29581355,Insidious: The Last Key,6.1,2018-01-03
90,10000000,Comedy,364437,Lady Bird,7.5,2017-09-08
138,10000000,Drama,11719,Golden Exits,5.6,2018-02-09
84,10000000,Drama,125570,Wonder Wheel,6.2,2017-12-01
67,10000000,Comedy,1211345,The Disaster Artist,7.3,2017-11-30
32,10000000,Thriller,2840246,Suburbicon,5.5,2017-10-26
140,5741614,Romance,10841,Thelma,7.1,2017-09-15
89,3500000,Romance,412932,Call Me by Your Name,8.3,2017-10-27
129,0,Romance,5296,绣春刀II：修罗战场,7.3,2017-08-11
130,0,Documentary,3270,Rebels on Pointe,7.0,2017-02-03